name        : ardour
version     : 4.7.0
release     : 1
source      :
    - https://dl.dropboxusercontent.com/u/55730378/pkgsrc/a/Ardour-4.7.0.tar.bz2 : d08bb7702603b81ac46287640881076aa7e85ab629ad3b454aae6aa61d6e1d01
license     :
    - GPL-3.0
component   : multimedia.audio
summary     : Professional-grade digital audio workstation
builddeps   :
    - pkgconfig(atkmm-1.6)
    - pkgconfig(gtkmm-2.4)
    - alsa-lib-devel
    - aubio-devel
    - curl-devel
    - fftw-devel
    - itstool
    - jack-audio-connection-kit-devel
    - libboost-devel
    - libcairo-devel
    - libgtk-2-devel
    - libflac-devel
    - liblo-devel
    - libogg-devel
    - libsamplerate-devel
    - libsndfile-devel
    - libxml2-devel
    - lilv-devel
    - lrdf-devel
    - python
    - raptor2-devel
    - rubberband-devel
    - serd-devel
    - sord-devel
    - sratom-devel
    - suil-devel
    - taglib-devel
    - vamp-plugin-sdk-devel
description : |
    Ardour is a professional DAW aimed for audio engineers, musicians and composers with many features like: unlimited tracks, LADSPA/LV2 support, powerful routing, video sync and much more.
setup       : |
    %workdir%/waf configure --prefix=%PREFIX% --libdir=%libdir% --cxx11 --with-backends=dummy,jack,alsa --freedesktop --no-lxvst --optimize
build       : |
    %workdir%/waf build
install     : |
    %workdir%/waf install --destdir="$installdir"
    
    mv "$installdir/usr/bin/ardour4" "$installdir/usr/bin/ardour"
    sed -i 's/ardour4/ardour/g' %workdir%/build/gtk2_ardour/ardour4.desktop

    for size in 16 22 32 48 256 512; do
        mkdir -p "$installdir/usr/share/icons/hicolor/${size}x${size}/apps"
        install -m 0644 %workdir%/gtk2_ardour/icons/ardour_icon_${size}px.png "$installdir/usr/share/icons/hicolor/${size}x${size}/apps/ardour.png"
    done
    
    mkdir -p "$installdir/usr/share/applications"
    install -m 0644 %workdir%/build/gtk2_ardour/ardour4.desktop "$installdir/usr/share/applications/ardour.desktop"
