name       : ardour
version    : '7.4'
release    : 36
source     :
    - git|https://github.com/Ardour/ardour.git : 7.4
license    : GPL-3.0-or-later
component  : multimedia.audio
homepage   : https://ardour.org/
summary    : Professional-grade digital audio workstation
description: |
    Ardour is a professional DAW aimed for audio engineers, musicians and composers with many features like: unlimited tracks, LADSPA/LV2 support, powerful routing, video sync and much more.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(aubio)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(fluidsynth)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(hidapi-hidraw)
    - pkgconfig(jack)
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(liblo)
    - pkgconfig(libpulse-simple)
    - pkgconfig(libusb-1.0)
    - pkgconfig(ltc)
    - pkgconfig(lrdf)
    - pkgconfig(lilv-0)
    - pkgconfig(ogg)
    - pkgconfig(raptor2)
    - pkgconfig(rubberband)
    - pkgconfig(samplerate)
    - pkgconfig(serf-1)
    - pkgconfig(sndfile)
    - pkgconfig(sord-0)
    - pkgconfig(soundtouch)
    - pkgconfig(sratom-0)
    - pkgconfig(suil-0)
    - pkgconfig(taglib)
    - pkgconfig(vamp)
    - itstool
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-internal-qm-dsp.patch

    %waf_configure -j1 \
        --use-external-libs \
        --cxx11 \
        --optimize \
        --freedesktop \
        --no-phone-home \
        --libdir=%libdir% \
        --with-backends=alsa,dummy,jack,pulseaudio
build      : |
    %waf_build -j4
install    : |
    %waf_install

    for size in 16 22 32 48 256 512; do
        install -Dm0644 $workdir/gtk2_ardour/resources/Ardour-icon_${size}px.png $installdir/usr/share/icons/hicolor/${size}x${size}/apps/ardour.png
    done

    install -Dm00644 $workdir/gtk2_ardour/resources/Ardour-icon_512px.png $installdir/usr/share/pixmaps/ardour.png

    # Install desktop file and fix icon name by removing version
    mv $installdir/usr/share/applications/ardour7.desktop $installdir/usr/share/applications/ardour.desktop
    sed -i 's/Icon=ardour7/Icon=ardour/g' $installdir/usr/share/applications/ardour.desktop
    mv $installdir/usr/share/appdata/ardour7.appdata.xml $installdir/usr/share/appdata/ardour.appdata.xml

    # Add mimetype info for .ardour s	ession files.
    install -Dm00644 build/gtk2_ardour/ardour.xml $installdir/usr/share/mime/packages/ardour.xml
