name       : ardour
version    : 4.7.0
release    : 1
source     :
    - http://stroblindustries.com/solus-tarballs/Ardour-4.7.0.tar.bz2 : d08bb7702603b81ac46287640881076aa7e85ab629ad3b454aae6aa61d6e1d01
license    : GPL-3.0
component  : multimedia.audio
summary    : Professional-grade digital audio workstation
description: |
    Ardour is a professional DAW aimed for audio engineers, musicians and composers with many features like: unlimited tracks, LADSPA/LV2 support, powerful routing, video sync and much more.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(aubio)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(jack)
    - pkgconfig(libcurl)
    - pkgconfig(liblo)
    - pkgconfig(lrdf)
    - pkgconfig(lilv-0)
    - pkgconfig(ogg)
    - pkgconfig(python-2.7)
    - pkgconfig(raptor2)
    - pkgconfig(rubberband)
    - pkgconfig(samplerate)
    - pkgconfig(serf-1)
    - pkgconfig(sndfile)
    - pkgconfig(sord-0)
    - pkgconfig(sratom-0)
    - pkgconfig(suil-0)
    - pkgconfig(taglib)
    - pkgconfig(vamp)
    - itstool
    - libboost-devel
setup      : |
    ./waf configure --prefix=/usr \
        --cxx11 \
        --freedesktop \
        --libdir=%libdir% \
        --no-lxvst \
        --optimize \
        --with-backends=dummy,jack,alsa
build      : |
    ./waf build
install    : |
    ./waf install --destdir="$installdir"

    for size in 16 22 32 48 256 512; do
        install -Dm0644 %workdir%/gtk2_ardour/icons/ardour_icon_${size}px.png $installdir/usr/share/icons/hicolor/${size}x${size}/apps/ardour4.png
    done

    install -Dm0644 $workdir/build/gtk2_ardour/ardour4.desktop $installdir/usr/share/applications/ardour4.desktop
