name       : ardour
version    : '5.12'
release    : 17
source     :
    - git|https://github.com/Ardour/ardour.git : 5.12
license    : GPL-3.0-or-later
component  : multimedia.audio
summary    : Professional-grade digital audio workstation
description: |
    Ardour is a professional DAW aimed for audio engineers, musicians and composers with many features like: unlimited tracks, LADSPA/LV2 support, powerful routing, video sync and much more.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atkmm-1.6)
    - pkgconfig(aubio)
    - pkgconfig(fftw3)
    - pkgconfig(flac)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtkmm-2.4)
    - pkgconfig(libarchive)
    - pkgconfig(libcurl)
    - pkgconfig(libusb-1.0)
    - pkgconfig(liblo)
    - pkgconfig(lrdf)
    - pkgconfig(lilv-0)
    - pkgconfig(ogg)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(python-2.7)
    - pkgconfig(raptor2)
    - pkgconfig(rubberband)
    - pkgconfig(samplerate)
    - pkgconfig(serf-1)
    - pkgconfig(sndfile)
    - pkgconfig(sord-0)
    - pkgconfig(sratom-0)
    - pkgconfig(suil-0)
    - pkgconfig(taglib)
    - pkgconfig(vamp)
    - itstool
    - libboost-devel
setup      : |
    %waf_configure -j1 \
        --cxx11 \
        --freedesktop \
        --libdir=%libdir% \
        --optimize \
        --with-backends=alsa,dummy
build      : |
    %waf_build
install    : |
    %waf_install

    for size in 16 22 32 48 256 512; do
        install -Dm0644 $workdir/gtk2_ardour/resources/Ardour-icon_${size}px.png $installdir/usr/share/icons/hicolor/${size}x${size}/apps/ardour.png
    done

    install -Dm0644 $workdir/gtk2_ardour/resources/Ardour-icon_512px.png $installdir/usr/share/pixmaps/ardour.png
    install -Dm0644 $pkgfiles/ardour.desktop $installdir/usr/share/applications/ardour.desktop
